use aletheia_core::pack::EvidencePack;
use aletheia_core::verify::verify_pack;
use std::fs;
use std::io::Write;

// Embed HTML template at compile time.
const REPORT_HTML: &str = include_str!("templates/report.html");

pub fn run(
    format: String,
    pack: String,
    output: Option<String>,
) -> Result<(), Box<dyn std::error::Error>> {
    let json_str = fs::read_to_string(&pack)
        .map_err(|e| format!("cannot read pack file '{}': {}", pack, e))?;

    let evidence: EvidencePack = serde_json::from_str(&json_str)
        .map_err(|e| format!("invalid evidence pack: {}", e))?;

    let rendered = match format.to_lowercase().as_str() {
        "json" => serde_json::to_string_pretty(&evidence)?,
        "markdown" | "md" => render_markdown(&evidence),
        "html" => render_html(&evidence, &json_str),
        other => return Err(format!("unknown format '{}'; supported: json, markdown, html", other).into()),
    };

    match output {
        Some(path) => {
            fs::write(&path, rendered.as_bytes())?;
            eprintln!("Exported to {}", path);
        }
        None => {
            let stdout = std::io::stdout();
            stdout.lock().write_all(rendered.as_bytes())?;
        }
    }

    Ok(())
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(ch),
        }
    }
    out
}

fn truncate_payload(value: &serde_json::Value, max_len: usize) -> String {
    let s = value.to_string();
    if s.len() <= max_len {
        s
    } else {
        format!("{}…", &s[..max_len])
    }
}

fn timestamp_display(millis_or_secs: u64) -> String {
    // sealed_at / created_at are Unix seconds in the pack
    // chrono expects milliseconds for from_timestamp_millis
    let millis = if millis_or_secs < 1_000_000_000_000 {
        // looks like seconds
        millis_or_secs * 1000
    } else {
        millis_or_secs
    };
    chrono::DateTime::from_timestamp_millis(millis as i64)
        .map(|dt| dt.format("%Y-%m-%d %H:%M:%S UTC").to_string())
        .unwrap_or_else(|| millis_or_secs.to_string())
}

// ── Markdown renderer ─────────────────────────────────────────────────────────

fn render_markdown(pack: &EvidencePack) -> String {
    let verify_result = verify_pack(pack, None);
    let status = if verify_result.is_ok() { "verified" } else { "failed" };
    let merkle_hex = hex::encode(pack.merkle_root);
    let version = &pack.version;
    let event_count = pack.metadata.event_count;
    let sig_count = pack.signatures.len();

    let mut md = String::new();

    md.push_str("# Aletheia Evidence Report\n\n");
    md.push_str(&format!("**Session:** `{}`\n\n", pack.session_id));
    md.push_str(&format!("**Status:** {}\n\n", status));
    md.push_str(&format!("**Sealed at:** {}\n\n", timestamp_display(pack.sealed_at)));

    md.push_str("## Summary\n\n");
    md.push_str("| Field | Value |\n");
    md.push_str("|---|---|\n");
    md.push_str(&format!("| Events | {} |\n", event_count));
    md.push_str(&format!("| Merkle Root | `{}` |\n", merkle_hex));
    md.push_str(&format!("| Signatures | {} |\n", sig_count));
    md.push_str(&format!("| Version | {} |\n", version));

    md.push_str("\n## Event Timeline\n\n");
    for receipt in &pack.receipts {
        let payload_str = truncate_payload(&receipt.event.payload, 80);
        md.push_str(&format!(
            "- **[{}]** `{}` / `{:?}` — {}\n",
            receipt.sequence,
            receipt.event.source,
            receipt.event.kind,
            payload_str,
        ));
    }

    md.push_str("\n## Hash Chain\n\n");
    md.push_str("```\n");
    for receipt in &pack.receipts {
        let hash_hex = hex::encode(receipt.hash);
        let prev_hex = hex::encode(receipt.prev_hash);
        md.push_str(&format!(
            "{}: {} ← {}\n",
            receipt.sequence,
            &hash_hex[..16],
            &prev_hex[..16],
        ));
    }
    md.push_str("```\n");

    md.push_str(&format!("\n---\n_Generated by Aletheia v{}_\n", version));

    md
}

// ── HTML renderer ─────────────────────────────────────────────────────────────

fn render_html(pack: &EvidencePack, raw_json: &str) -> String {
    let verify_result = verify_pack(pack, None);
    let (status_class, status_text) = if verify_result.is_ok() {
        ("verified", "Verified")
    } else {
        ("failed", "Verification Failed")
    };

    let merkle_hex = hex::encode(pack.merkle_root);
    let version = &pack.version;
    let event_count = pack.metadata.event_count;
    let sig_count = pack.signatures.len();

    let chain_status = if verify_result.as_ref().map(|r| r.chain_ok).unwrap_or(false) {
        "OK"
    } else {
        "FAILED"
    };
    let sig_status = if sig_count == 0 {
        "unsigned".to_string()
    } else {
        format!("{} signature(s)", sig_count)
    };

    // Build timeline rows
    let mut timeline_rows = String::new();
    for receipt in &pack.receipts {
        let payload_str = html_escape(&truncate_payload(&receipt.event.payload, 100));
        let source = html_escape(&receipt.event.source);
        let kind = html_escape(&format!("{:?}", receipt.event.kind));
        timeline_rows.push_str(&format!(
            "<tr><td>{}</td><td>{}</td><td>{}</td><td class=\"mono\">{}</td></tr>\n",
            receipt.sequence, source, kind, payload_str
        ));
    }

    // Build hash chain rows
    let mut chain_rows = String::new();
    for receipt in &pack.receipts {
        let hash_hex = hex::encode(receipt.hash);
        let prev_hex = hex::encode(receipt.prev_hash);
        chain_rows.push_str(&format!(
            "<tr><td>{}</td><td class=\"mono\">{}</td><td class=\"mono\">{}</td></tr>\n",
            receipt.sequence,
            &hash_hex[..16],
            &prev_hex[..16],
        ));
    }

    // Build signatures section
    let signatures_html = if pack.signatures.is_empty() {
        "<p><em>No signatures present.</em></p>".to_string()
    } else {
        let mut table = String::from(
            "<table><thead><tr><th>Signer (public key)</th><th>Signature</th><th>Signed At</th></tr></thead><tbody>\n",
        );
        for sig in &pack.signatures {
            let signer = html_escape(&sig.signer);
            let signature = html_escape(&sig.signature);
            let signed_at = timestamp_display(sig.signed_at);
            table.push_str(&format!(
                "<tr><td class=\"mono\">{}</td><td class=\"mono\">{}</td><td>{}</td></tr>\n",
                signer, signature, signed_at
            ));
        }
        table.push_str("</tbody></table>");
        table
    };

    REPORT_HTML
        .replace("{{SESSION_ID}}", &html_escape(&pack.session_id))
        .replace("{{SEALED_AT}}", &html_escape(&timestamp_display(pack.sealed_at)))
        .replace("{{STATUS_CLASS}}", status_class)
        .replace("{{STATUS_TEXT}}", status_text)
        .replace("{{EVENT_COUNT}}", &event_count.to_string())
        .replace("{{CHAIN_STATUS}}", chain_status)
        .replace("{{MERKLE_ROOT}}", &merkle_hex)
        .replace("{{SIGNATURES_STATUS}}", &html_escape(&sig_status))
        .replace("{{TIMELINE}}", &timeline_rows)
        .replace("{{HASH_CHAIN}}", &chain_rows)
        .replace("{{SIGNATURES}}", &signatures_html)
        .replace("{{RAW_JSON}}", &html_escape(raw_json))
        .replace("{{VERSION}}", &html_escape(version))
}
